In [1]:
import numpy as np


<div style="width:image width px; font-size:100%; text-align:center;"><img src='cbow_model_architecture.png' alt="alternate text" width="width" height="height" style="width:917;height:337;" /> Figure 1 </div>

# ReLU 
\begin{align}
 \mathbf{z_1} &= \mathbf{W_1}\mathbf{x} + \mathbf{b_1}  \tag{1} \\
 \mathbf{h} &= \mathrm{ReLU}(\mathbf{z_1})  \tag{2} \\
\end{align}

In [2]:
np.random.seed(10)

In [4]:
z1= 10 * np.random.rand(5,1) - 5

In [5]:
z1

array([[ 2.71320643],
       [-4.79248051],
       [ 1.33648235],
       [ 2.48803883],
       [-0.01492988]])

In [6]:
h = z1.copy()

In [7]:
h<0

array([[False],
       [ True],
       [False],
       [False],
       [ True]])

In [8]:
h[h<0] = 0

In [9]:
h

array([[2.71320643],
       [0.        ],
       [1.33648235],
       [2.48803883],
       [0.        ]])

In [14]:
np.max(h,0)

array([2.71320643])

In [20]:
np.array([max(i,0) for i in h])

array([[2.71320643],
       [0.        ],
       [1.33648235],
       [2.48803883],
       [0.        ]])

In [15]:
for i in h:
    if i<0:
        h[i] = 0
h

        

array([[2.71320643],
       [0.        ],
       [1.33648235],
       [2.48803883],
       [0.        ]])

In [16]:
def relu(z):
    result = z.copy()
    result[result<0]=0
    return result
    

In [17]:
z1

array([[ 2.71320643],
       [-4.79248051],
       [ 1.33648235],
       [ 2.48803883],
       [-0.01492988]])

In [18]:
relu(z1)

array([[2.71320643],
       [0.        ],
       [1.33648235],
       [2.48803883],
       [0.        ]])

# Softmax

\begin{align}
 \mathbf{z_2} &= \mathbf{W_2}\mathbf{h} + \mathbf{b_2}   \tag{3} \\
 \mathbf{\hat y} &= \mathrm{softmax}(\mathbf{z_2})   \tag{4} \\
\end{align}


$$ \textrm{softmax}(\textbf{z})_i = \frac{e^{z_i} }{\sum\limits_{j=1}^{V} e^{z_j} }  \tag{5} $$



In [24]:
z=np.array([9,8,11,10,8.5])

In [25]:
z

array([ 9. ,  8. , 11. , 10. ,  8.5])

In [26]:
np.exp(z)

array([ 8103.08392758,  2980.95798704, 59874.1417152 , 22026.46579481,
        4914.7688403 ])

In [27]:
np.sum(np.exp(z))

97899.41826492078

In [28]:
np.exp(z)/np.sum(np.exp(z))

array([0.08276948, 0.03044919, 0.61158833, 0.22499077, 0.05020223])

In [29]:
def softmax(z):
    e_z= np.exp(z)
    sum_ez = np.sum(e_z)
    return e_z / sum_ez

In [30]:
softmax(z)

array([0.08276948, 0.03044919, 0.61158833, 0.22499077, 0.05020223])